### ISSUE TITLE
How to make new scheme persistent?

### ISSUE THREAD

**Issue by rjrich** [scottclowe/matlab-schemer#41] opened 2023-02-25 18:11 UTC
I am new to Matlab and to matlab-schemer. I am running Matlab 2022b_r3 on Linux (Linux Mint 21.1 Xfce, based on Ubuntu 22.04 LTS). I have managed to use matlab-schemer to switch from the Matlab default color scheme to the cobalt scheme, but when I close Matlab and restart it, the color scheme has reverted to the Matlab default light color scheme. Is there a way to make the matlab-schemer cobalt scheme persistent so that Matlab starts up with the cobalt scheme?

**Comment by scottclowe** [comment] 2023-02-27 16:26
That's unexpected, as the scheme is supposed to persist between closing and reopening MATLAB. It does the same thing as if you manually go in the preferences dialog and set the customizable GUI colours. If you manually set one of the colours in the preferences, does that persist between closing and reopening MATLAB?

**Comment by rjrich** [comment] 2023-02-27 17:06
Thanks for your reply. I tried setting colors in the preferences and then
Apply followed by OK. I then quit matlab and launched it again, but the
colors had reverted to the matlab default light scheme.

**Comment by scottclowe** [comment] 2023-02-27 20:15
Okay, in that case its not an issue with Schemer, it's an issue with your MATLAB installation.

I think it this issue can be caused by installing MATLAB as root and running it as a user without sudo privileges. My recommendations are:
- Launch matlab from the terminal and check to see if an error message is displayed.
- Run the command `prefdir` in MATLAB to see where your preferences directory is, and then in terminal use `ls` to check the permissions for that directory and the preferences file within it. You may want to set it so all users can read and write that directory `chmod a+rw -R DIRNAME`.
- Check existing MATLAB support tickets on this topic to see if they fix your issue, e.g. https://www.mathworks.com/matlabcentral/answers/1777865-matlab-preferences-not-being-saved-across-sessions
- Reinstall MATLAB

I will close this issue now, as it is not a problem with Schemer.

If you debug and find a solution to your problem, please post here so others will know a solution to try if they face the same problem and happen upon this post.

**Closed as completed by scottclowe** 2023-02-27 20:15 UTC

**Comment by rjrich** [comment] 2023-02-27 21:14
- Launching matlab from the terminal did not display any errors.
- Changing file permissions on prefdir did not remedy the problem.
- However, the following fix **_did_** correct the problem:
https://www.mathworks.com/matlabcentral/answers/1806255-why-aren-t-my-matlab-preferences-saved-on-linux
Thanks!
