### ISSUE TITLE
Wrong background color on selected variables after restoring schemes

### ISSUE THREAD

**Issue by LoGGoL** [scottclowe/matlab-schemer#11] opened 2015-11-16 08:37 UTC
Hi,
I observe another issue with the matlab_schemer.
![image](https://cloud.githubusercontent.com/assets/15728990/11177331/19c11e12-8c45-11e5-819a-ff6957e8a899.png)

This happens, when I export my current scheme, load another scheme from the scheme folder and then restore my saved scheme back. Also the M-Lint hints on the right side are black and not orange.

Regards,

**Comment by scottclowe** [comment] 2015-11-16 12:22
Hi @LoGGoL,

I was not able to reproduce the bug. It seems that `schemer_export` has erroneously outputted black for the M-Lint background and warning colours.

If this is correct, the exported scheme will contain these lines:
```
Colors_M_Warnings=C-16777216
ColorsMLintAutoFixBackground=C-16777216
```
- Can you check for me that this is the case?

The reason will be because unassigned colours (colours which have never been changed from the default since installing MATLAB) are returned as black when using the function to fetch the preference colour - `com.mathworks.services.Prefs.getColorPref`. As far as I have been able to ascertain, there is no way of telling whether a specific colour is unassigned or genuinely is black.

Currently, the only solution is to ensure every colour is assigned by manually setting every colour (even if it setting it to be the same as the default value, this still works). This is described in the help for `schemer_export`.

- Did you follow the `IMPORTANT NOTE:` section of the help for schemer_export before exporting?

If not, could you try this and see if it resolves the issue?

**Comment by scottclowe** [comment] 2016-04-25 18:45
This error should not have been possible since version v1.2.1, which introduced [checks for each preference panel to ensure the values have been set before exporting them].(https://github.com/scottclowe/matlab-schemer/commit/0bb4e679a10af83d8ebedb32e5551aabd37985f3)

Consequently, I do not understand how this issue has arisen. Without additional details on how to produce this error, I am unfortunately forced to close this bug with the issue unresolved.

If anyone experiences this bug again, please reopen this issue.

**Closed by scottclowe** 2016-04-25 18:45 UTC
Labels: bug, in progress
